"""changed the Message schema to make prompt decomposed into multiple parts

Revision ID: 0bf3eecb94b9
Revises: 7edf508910b3
Create Date: 2026-02-07 09:07:21.206907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf3eecb94b9'
down_revision: Union[str, Sequence[str], None] = '7edf508910b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('url_content', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('rag_content', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('request_content', sa.String(), nullable=False))
    op.drop_column('messages', 'prompt_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('prompt_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'request_content')
    op.drop_column('messages', 'rag_content')
    op.drop_column('messages', 'url_content')
    # ### end Alembic commands ###
