"""added githubid to users table

Revision ID: 10f6d1b1521d
Revises: dea8070ab94a
Create Date: 2026-02-12 20:46:51.714185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f6d1b1521d'
down_revision: Union[str, Sequence[str], None] = 'dea8070ab94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_ip_address'), table_name='tokens')
    op.drop_index(op.f('ix_token_user_id'), table_name='tokens')
    op.create_index(op.f('ix_tokens_ip_address'), 'tokens', ['ip_address'], unique=False)
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'github_id')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_ip_address'), table_name='tokens')
    op.create_index(op.f('ix_token_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_ip_address'), 'tokens', ['ip_address'], unique=False)
    # ### end Alembic commands ###
