"""add thinking_content to messages

Revision ID: 1c17c9852f08
Revises: facb84c0440e
Create Date: 2026-02-16 13:30:26.399948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c17c9852f08'
down_revision: Union[str, Sequence[str], None] = 'facb84c0440e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'thinking_content')
    # ### end Alembic commands ###
