"""removed the nullable from response field in Message

Revision ID: 46d01958670b
Revises: 96f6d3023da9
Create Date: 2026-02-06 20:35:57.982981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d01958670b'
down_revision: Union[str, Sequence[str], None] = '96f6d3023da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'response_content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'response_content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
