"""updated all user and token ids to use uuid4

Revision ID: 84bd6ee2331e
Revises: e93d8381d7a6
Create Date: 2026-02-09 11:03:07.760567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84bd6ee2331e"
down_revision: Union[str, Sequence[str], None] = "e93d8381d7a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Can't convert INTEGER to UUID directly, need to drop and recreate
    # First drop the primary key constraint
    op.drop_constraint("tokens_pkey", "tokens", type_="primary")
    op.drop_column("tokens", "id")

    # Recreate as UUID
    op.add_column(
        "tokens",
        sa.Column(
            "id", sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")
        ),
    )
    op.create_primary_key("tokens_pkey", "tokens", ["id"])

    # Remove the server_default after adding (optional, matches model behavior)
    op.alter_column("tokens", "id", server_default=None)

    op.add_column("users", sa.Column("username", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.alter_column(
        "tokens",
        "id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
