"""made all updated_at and created_at user derver side time for consistentcy

Revision ID: 8c4238681710
Revises: 84bd6ee2331e
Create Date: 2026-02-09 14:18:50.115079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4238681710'
down_revision: Union[str, Sequence[str], None] = '84bd6ee2331e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_token_user_id', 'tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_user_id', table_name='tokens')
    # ### end Alembic commands ###
